# Site settings
title: Tilo Westermann
email: mail@tilowestermann.eu
description: HCI Researcher
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://tilowestermann.eu"
twitter_username: tilowestermann
github_username:  tilowestermann
so_username: 184245
linkedin_username: tilowestermann
xing_username: Tilo_Westermann

# Build settings
markdown: kramdown
